services:
  devserver:
    image: 'node:18-alpine'
    user: 'node'
    working_dir: /home/node/app
    environment:
      - NODE_ENV=development
      - DEV_SERVER_PORT=5500
    ports:
      - '5500:5500'
    volumes:
      - ../../src:/home/node/app/src
      - ../../node_modules:/home/node/app/node_modules
      - ../../config/:/home/node/app/config
      - ../../package.json:/home/node/app/package.json
      - ../../package-lock.json:/home/node/app/package-lock.json
    command: 'npm start'